functions = "./tests"
view = "image-classification"
metadata = "./metadata_f.parquet"
data_path = "https://diffusiondb.m4ke.org/"
data_column = "image_name"
id_column = "image_name"
label_column = "prompt"
calculate_histogram_metrics = false
batch_size = 100000
port = 8012